tags:
  - name: Events
    description: Events API endpoints
  - name: Availability
    description: Availability API endpoints

paths:
  # [GET] events
  /events:
    get:
      tags:
        - Events
      summary: Get All Events or Events in a Date Range
      parameters:
        - name: startDate
          in: query
          description: Date in ISO 8601 format eg. 2023-01-24T09:00:00.000+05:30
          schema:
            type: date
        - name: endDate
          in: query
          description: Date in ISO 8601 format eg. 2023-01-24T09:00:00.000+05:30
          schema:
            type: date
        - name: timezone
          in: header
          description: Timezone in ISO 8601 format eg. Asia/Kolkata.
          schema:
            type: string
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [POST] events
    post:
      tags:
        - Events
      summary: Add New Event
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                time:
                  type: string
                duration:
                  type: integer
              example: # Sample object
                time: '2023-01-24T09:00:00.000+05:30'
                duration: 30
      responses:
        201:
          description: 'Event Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflicting Event Found'
        500:
          description: 'Server Error'
  /availability:
    # [GET] availability
    get:
      tags:
        - Availability
      summary: Get Free Slots in a Date Range
      parameters:
        - name: startDate
          in: query
          description: startDate
          required: true
          type: date
        - name: endDate
          in: query
          description: endDate
          required: true
          type: date
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

schemes:
  - https
  - http
